### PR TITLE
added dependencies on helpers

### PR DESCRIPTION
**Pull request by PablitoGS**
Added dependencies, script tasks and import mixins from base for helpers
Please review @nguasch @larnedo @nucliweb

### CODE REVIEW

**Comment by nguasch** [comment]
have been added /docs and /dist directories, because .gitignore file is empty.

Please @PablitoGS, can you review this?

**Comment by PablitoGS** [comment]
Added gitignore on helpers

**Comment by nguasch** [comment]
:+1:  but I don't know if 
.editorconfig
.eslintrc
.sass-lint.yml
files should be on .getignore because are generated by npm dependencies. What do you think about that @nucliweb ?

**Comment by nucliweb** [comment]
Always we need .editorconfig for all repos, is the config for editor.
For this repo we don't need config linters files for `js`& `Sass`

**Comment by PablitoGS** [comment]
I added precommit rules files on gitignore, review please @nguasch @nucliweb

**Comment by nguasch** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
